- name: "add public ssh key to digitalocean account"
  digital_ocean_sshkey:
    name: "dev1"
    oauth_token: "{{ digital_ocean_token }}"
    ssh_pub_key: "{{lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
  register: sshkey_result

- name: Create a new droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: "{{ droplet_name }}"
    oauth_token: "{{ digital_ocean_token }}"
    size: "{{ droplet_size }}"
    region: "{{ droplet_region }}"
    image: "{{ droplet_image }}"
    wait_timeout: 500
    ssh_keys: ["{{ sshkey_result.data.ssh_key.id }}"] 
  register: my_droplet

- debug:
    msg: "ID is {{ my_droplet.data.droplet.id }}, IP is {{ my_droplet.data.ip_address }}"

- name: Add host
  add_host:
    name: '{{ my_droplet.data.ip_address }}'
    groups: LTC_NODES

# - name: Pause for 1 minute because digital ocean seems to be having issues
#   pause:
#     minutes: 1

- name: "Update inventory file"
  delegate_to: localhost
  ini_file:
    dest: "/etc/ansible/hosts"
    section: "{{ target_group }}"
    option: "{{ my_droplet.data.ip_address }} # added by role"
    #value: "{{  }}"
    no_extra_spaces: yes
    mode: 0666
    state: present
    backup: no